# Generated by Django 4.2.10 on 2024-03-04 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0008_alter_recipe_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
